# Generated by Django 3.0.8 on 2020-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200821_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(verbose_name='date due'),
        ),
    ]
