# Generated by Django 3.0.8 on 2020-08-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_roworder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default='ben', max_length=200),
            preserve_default=False,
        ),
    ]
